INSERT INTO TBL_CATEGORY (NAME)  VALUES ('Fabricacao Propria');
INSERT INTO TBL_CATEGORY (NAME)  VALUES ('Nacional');
INSERT INTO TBL_CATEGORY (NAME)  VALUES ('Importado');
INSERT INTO TBL_CATEGORY (NAME)  VALUES ('Premium');
